Ios/live data
MapsIndoors/mapsindoors.github.io pull request #129
Opened 2020-08-10 10:32 UTC by Daniel-Nielsen

@marksdk, here is a draft for Live Data docs in iOS

2020-08-19 21:51 UTC, marksdk requested changes

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +This guide gives an overview of how to work with live data in the MapsIndoors iOS SDK. As opposed to static data that does not change unless data is synchronized, Live Data can change in real time an
```suggestion
This guide gives an overview of how to work with _Live Data_ in the MapsIndoors iOS SDK. As opposed to _static data_, which does not change unless data is synchronized, Live Data can change in real time, and these changes can be instantly reflected on the map and in searches.
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +* Changing the appearance of meeting rooms or workspace desks on a map or in a list, based on occupancy information.
```suggestion
* Changing the appearance of meeting rooms or workspace desks on a map, or in a list, based on occupancy information.
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +All live data is ordered in so called _topics_. A MapsIndoors topic is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components:
```suggestion
All Live Data is ordered in so-called _Topics_. A MapsIndoors Topic is _hierarchical_ in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components:
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +As a minimum, all topics relate to a dataset, also known as a solution in MapsIndoors, a Domain Type and one or more of the other components.
```suggestion
As a minimum, all Topics relate to a Data Set (also known as a "Solution" in MapsIndoors), a Domain Type and one (or more) of the other components.
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +The Domain Type describes what kind of conceptual domain the Live Data belongs to. Here are some examples of Domain Types:
```suggestion
The Domain Type describes what kind of conceptual Domain the Live Data belongs to. Here are some examples of Domain Types:
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +Support for live data requires that server-side integrations are in place. For example, visualizing live occupancy data requires that a calendar or booking system integration is in place. An integrat
```suggestion
Support for Live Data requires that server-side integrations are in place. For example, visualizing live occupancy data requires that a calendar or booking system integration is in place. An integration like that is set up in [collaboration with MapsPeople](https://www.mapspeople.com/mapsindoors-integrations/).
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +* Occupancy - The current known occupancy of a given capacity for example in a meeting room
```suggestion
* Occupancy - The current known occupancy of a given capacity, for example in a meeting room
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +Knowing that updates is ordered in Topics, it is possible to subscribe to updates using a Topic Criteria. Filtering out Live Updates can be done on all levels of the Topic Criteria. For example, you
```suggestion
Knowing that updates is ordered in Topics, it is possible to subscribe to updates using a Topic Criteria. Filtering out live updates can be done on all levels of the Topic Criteria. For example, you might want to subscribe to all position updates but only for a particular Floor in a particular Building. This can be done by setting the correct IDs on the Floor and Building component. Leaving out a component means that we will get all updates, regardless of what relation the updates have at that level. Continuing the example, leaving out the Floor component means that we get all position updates on all Floors, but still only for a particular Building.
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +A live update is the model for a message carrying one piece of live data, for example that a particular room is now occupied. It contains the topic for the live update and the actual live properties
```suggestion
A live update is the model for a message carrying one piece of Live Data, for example that a particular room is now occupied. It contains the Topic for the live update and the actual live properties as a _dictionary_ of _strings_.
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +To enable live data in an application, a subscription to one or more topics is needed. Once subscribed, the application can be notified about changes and can decide what to do. The application is in
```suggestion
To enable Live Data in an application, a subscription to one or more Topics is needed. Once subscribed, the application can be notified about changes and decide what to do. The application is in control of what should happen on Live Data updates, and the MapsIndoors SDKs provide mechanisms to efficiently make updates to the map representation of locations. The central class to carry out these tasks is the `LiveDataManager`.
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +The only Live Updates that is also directly notified to the SDK internally are Live Updates with the Position Domain Type. By consequense, if you have already set up your map with MapsIndoors, an add
```suggestion
The only Live Data updates that are also directly notified to the SDK internally are Live Data updates of the "Position" Domain Type. By consequense, if you have already set up your map with MapsIndoors, an additional few lines of code can enable moving locations on the map. Here is an example in Swift:
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +In the example the Topic was created with only the Domain Type. This will subscribe to all coming position updates for the dataset and if the updates are relevant for the particular view of the map,
```suggestion
In the example the Topic was created with only the Domain Type. This will subscribe to all coming position updates for the dataset, and if the updates are relevant for the particular view of the map, you will see moving icons on the map.
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +1. On a general level through `MPLiveDataManagerDelegate`, which is suitable in scenarios where all Live Updates might potentially affect the end users decisions, for example when searching broadly f
```suggestion
1. On a general level through `MPLiveDataManagerDelegate`, which is suitable in scenarios where all Live Updates might potentially affect the end user's decisions, for example when searching broadly for an available meeting room.
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +2. On a map-specific level through `MPMapControlDelegate`, which is suitable in scenarios where the map is the context for the users actions, for example when browsing the map for an available meetin
```suggestion
2. On a map-specific level through `MPMapControlDelegate`, which is suitable in scenarios where the map is the context for the user's actions, for example when browsing the map for an available meeting room nearby.
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/index.md
> +In order to get notified about state changes and errors happening in the Live Data Manager, `MPLiveDataManagerDelegate` utilizes other methods as shown in below example:
```suggestion
In order to get notified about state changes and errors happening in the Live Data Manager, `MPLiveDataManagerDelegate` utilizes other methods as shown in the example below:
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/live-data-tutorial.md
> +In this tutorial you will learn to work with Live Updates / Real Time Data in MapsIndoors. It is recommended that you read the [Live Data Introduction](/ios/v3/live-data) before continueing.
```suggestion
In this tutorial you will learn to work with Live Updates / real-time data in MapsIndoors. It is recommended that you read the [Live Data Introduction](/ios/v3/live-data) before continuing.
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/live-data-tutorial.md
> +We will create a view controller displaying a map that shows the some dynamic changes that are initiated from Live Data sources known by MapsIndoors. The test data coming as Live Updates contains dat
```suggestion
We will create a view controller displaying a map that shows some dynamic changes that are initiated from Live Data sources known by MapsIndoors. The test data are of the Occupancy Domain Type and the Position Domain Type.
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/live-data-tutorial.md
> +Add a method `toggleSubscription()` that does the actual toggling of a subscription for a button based on the buttons `isSelected` flag. Swap current selected state for button. If the flag is true an
```suggestion
}
```

Add a method `toggleSubscription()` that does the actual toggling of a subscription for a button based on the button's `isSelected` flag. Swap current selected state for button. If the flag is `true` and the button is selected, call the Live Data Manager's `subscribe()` method with the given Topic Criteria. We will also call a `startFlash()`method that should make the button flash. More on this later. If the flag is `false` and the button is not selected, call the Live Data Manager's `unsubscribe()` method with the given Topic Criteria. Similarly we will call a `stopFlash()`method that should stop the button flash.
```

2020-08-19 21:51 UTC, marksdk commented on collections/_ios/v3/live-data/live-data-tutorial.md
> +Inside `viewDidLoad()`, also request a building and go to this building on the map.
```suggestion
Inside `viewDidLoad()`, also request a Building and go to this Building on the map.
```

2020-08-20 06:11 UTC, Daniel-Nielsen commented
Thanks @marksdk, much appreciated!!

2020-08-20 08:47 UTC, rocu-mapspeople commented on collections/_ios/v3/live-data/index.md
> +* Changing the appearance of meeting rooms or workspace desks on a map or in a list, based on occupancy information.
is there something specific about the appearance that we can be more descriptive about?  icons? colors etc?

2020-08-20 08:58 UTC, rocu-mapspeople commented on collections/_ios/v3/live-data/index.md
> +To enable live data in an application, a subscription to one or more topics is needed. Once subscribed, the application can be notified about changes and can decide what to do. The application is in
```suggestion
To enable live data in an application, a subscription to one or more topics is needed. Once subscribed, the application can be notified about changes and can decide what to do. The application is in control of what should happen upon receiving live data updates, and the MapsIndoors SDKs provide mechanisms to efficiently make updates to the map representation of locations. The central class to carry out these tasks is the LiveDataManager.
```

2020-08-20 08:58 UTC, rocu-mapspeople commented on collections/_ios/v3/live-data/index.md
> +Filtering of the topic can be done on all levels of the data model except DatasetID which must be specified. When setting up a topic subscription the following IDs can be specified or left as a “wild
Should there also include information/links on how/what displayRules are and getting subsets of locations via other relevant methods?

2020-09-01 13:56 UTC, marksdk approved these changes

2020-09-01 16:20 UTC, merged