Ios/3.12.0
MapsIndoors/mapsindoors.github.io pull request #142
Opened 2020-09-22 13:49 UTC by mbh-mapspeople

2020-09-23 07:21 UTC, Daniel-Nielsen requested changes

2020-09-23 07:21 UTC, Daniel-Nielsen commented on collections/_ios/v3/map-styling/index.md
> +For example a venue can appear as a marker-icon on low zoomlevels, when zooming in the venuename can appear, and zooming even more in the venua polygon can appear.
```suggestion
For example a venue can appear as a marker-icon on low zoomlevels, when zooming in the venuename can appear, and zooming even more in the venue polygon can appear.
```

2020-09-23 07:27 UTC, Daniel-Nielsen approved these changes

2020-10-05 21:44 UTC, marksdk commented
@mbh-mapspeople Don't forget to merge this one in if there are no conflicts with `main` 🙂

2020-10-06 12:32 UTC, Daniel-Nielsen commented
@marksdk, if I am not mistaken, this branch is waiting for the actual feature to be released.

2020-10-06 12:34 UTC, Daniel-Nielsen commented
Also, the version has been hijacked by the Live Data feature...

2020-10-15 10:58 UTC, closed without merging