Web documentation restructured
MapsIndoors/mapsindoors.github.io pull request #145
Opened 2020-09-25 10:49 UTC by sibo86

Web documentation has gotten an update - wording and fiddles. Guides have been added on each of the "tutorial" pages. A glossary is added under various.

2020-09-28 13:11 UTC, marksdk requested changes
Hey @sibo86,

I've commented here with a bunch of suggestions to changes. It looks like a lot, but it's small changes accumulated to a rather large review.

Let me know inline if I need to elaborate on a suggestion or comment.

Lastly, if you're using Visual Studio Code, there's a "Markdown linter" extension that will help the linting step go green as it fixes the issues it finds here when pushing code.

2020-09-30 07:51 UTC, sibo86 commented on collections/_web/v3/guides/dynamic-updates.md
> +![guides](/assets/various/Guides.png "guides")
I know that this is a hack hack as the Guides/Tutorial headlines wasn't easily accessible for using in this way - so it is made deliberately as I don't expect the page to "live" as is for a long period of time.

2020-09-30 07:54 UTC, sibo86 commented on collections/_web/v3/guides/dynamic-updates.md
> +******
The <br> tag is set to create some whitespace above the "hr" (which *** also forms). I cannot find any other way to make it so

2020-09-30 07:57 UTC, sibo86 commented on collections/_various/glossary.md
> +An Area is a geographic area covering a part of a Room’s polygon. It is not a Location, but a TK.
Fine by me - must admit I more or less just copied what was in the document on Drive:)

2020-09-30 12:01 UTC, marksdk approved these changes

2020-09-30 12:01 UTC, marksdk commented on collections/_various/glossary.md
> +### Location / Place / POI
@sibo86 This is the last outstanding issue. If there's a task to improve it later, we can keep it for now, but I think it needs a lift at some point regardless, and it's one of the things our SEs spend most time explaining to CMS users.

2020-09-30 12:18 UTC, merged