MIGEN-1692 - Added product overview
MapsIndoors/mapsindoors.github.io pull request #154
Opened 2020-10-13 06:53 UTC by sibo86

The front page has an extra button added

2020-10-13 11:27 UTC, marksdk requested changes

2020-10-13 11:27 UTC, marksdk commented on collections/_product/index.md
> +* An integration API
```suggestion
* A Content Management System (CMS)
* Three SDKs:
  * Android
  * iOS
  * JavaScript
* Standard apps built on top of each SDK 
* A kiosk web app
* An Integration API
```

2020-10-13 11:27 UTC, marksdk commented on collections/_product/index.md
> +When you order a MapsIndoors solution your organisation needs to provide MapsPeople with floor plans for each of the buildings you want to have indoor navigation for.
```suggestion
When you buy MapsIndoors your organisation needs to provide MapsPeople with floor plans for each of the buildings you want to have indoor navigation for.

```

2020-10-13 11:27 UTC, marksdk commented on collections/_product/index.md
> +When we receive these they will be digitised and positioned correctly in “the world” aka on the underlying Google Map. This is what we define as a solution, for which you will get a MapsIndoors API k
```suggestion
When we receive these they will be digitised and positioned correctly in “the world”. This is what we define as a Solution, for which you will get a MapsIndoors API key. Use this API key when working with the SDKs to access your data.
```

A few notes:

- All technical terms related to MapsIndoors should be kept capitalised (Solution, Building, Floor etc.)
- We should refrain from mentioning a specific map provider going forward, as we'll support multiple providers

2020-10-13 11:27 UTC, marksdk commented on collections/_product/index.md
> +When you have a custom MapsIndoors Solution you also get access to the MapsIndoors CMS. Within the CMS you can manage locations within your solution; create, remove, update locations such as rooms, c
```suggestion
When you have a custom MapsIndoors Solution you also get access to the MapsIndoors CMS. Within the CMS you can manage Locations within your Solution; create, remove, update Locations such as rooms, coffee machines etc. The content created within the CMS is the content that can be accessed and controlled via the SDKs.
```

Should we mention the option of removing rooms?

2020-10-13 11:27 UTC, marksdk commented on collections/_product/index.md
> +The CMS is used for day to day management if a location needs to be moved (could be a printer or a coffee machine), if rooms get new names (meeting rooms for example), if access needs to be restricte
```suggestion
The CMS is used for day-to-day management if a Location needs to be moved (could be a printer or a coffee machine), if Rooms get new names (meeting rooms for example), if access needs to be restricted to some Locations etc.
```

2020-10-13 11:27 UTC, marksdk commented on collections/_product/index.md
> +The SDKs enable you to build your own custom app on top or as an integral part of your existing app. The MapsIndoors SDKs are available for:
```suggestion
The SDKs enable you to build your own custom app on top of, or as an integral part of, your existing app. The MapsIndoors SDKs are available for:
```

2020-10-13 11:27 UTC, marksdk commented on collections/_product/index.md
> +![Platforms](/assets/product/Platforms.png "Platforms")
A comment on the use of these images: It's not great for search engines and accessibility in general. I think we should keep to using text as much as possible to make sure it's indexable and easily readable for humans and machines alike.

2020-10-13 11:27 UTC, marksdk commented on collections/_product/index.md
> +The MapsIndoors SDKs are the engine that makes sure that you can create a route from a Google location to one of your Indoor locations, it enables you to search in your indoor locations, set the pres
```suggestion
The MapsIndoors SDKs are the engines that makes sure you can create a route from a location in the world to one of your indoor locations, search your indoor locations, show the relevant information for a specific location etc. An exhaustive list of features within the SDKs can be found in the reference documentation for each platform.
```

2020-10-13 11:27 UTC, marksdk commented on collections/_product/index.md
> +MapsIndoors Standard Apps are built on top of the SDKs and visualises some of the SDK capabilities. They are more or less plug and play and provide a good basic indoor navigation app with a map, cate
```suggestion
MapsIndoors Standard Apps are built on top of the SDKs and visualises some of the SDK capabilities. They are more or less plug-and-play and provide a good basic indoor navigation app with a map, Category overview of Locations, search, directions and routing.
```

2020-10-13 11:27 UTC, marksdk commented on collections/_product/index.md
> +The MapsIndoors Standard App Suite also includes a plug and play Kiosk solution. The solution can be run on a kiosk stand and help one-time users of a facility to find their way without having an app
```suggestion
The MapsIndoors Standard App suite also includes a plug-and-play Kiosk web app. The app can be run on an information stand and help one-time users of a facility find their way without having an app - for example at a hospital.
```

2020-10-13 11:27 UTC, marksdk commented on collections/_product/index.md
> +Booking integrations are characterised by data flowing in and out of MapsIndoors (read/write). Room bookings can happen directly from MapsIndoors and/or be displayed on the MapsIndoors map. For examp
This should be revisited. The Integration API does not handle Live Data—the Integration API is only used for infrequent updates to the MapsIndoors Solution data.

2020-10-13 11:27 UTC, marksdk commented on collections/_product/index.md
> +MapsIndoors is primarily an Indoor Navigation Provider that can provide directions and guide users as well as present relevant information on the map.
```suggestion
MapsIndoors is an Indoor Navigation Provider that provides directions and guide users as well as present relevant information on the map.
```

2020-10-13 11:27 UTC, marksdk commented on collections/_product/index.md
> +In order to get precise user position indoors, dynamic turn-by-turn routing, location based advertising etc. an IPS should be put in place in the relevant building(s).
```suggestion

In order to get a precise user position indoors, dynamic turn-by-turn routing, location-based advertising etc. an Indoor Positioning System (IPS) should be put in place in the relevant building(s).
```

2020-10-13 11:27 UTC, marksdk commented on collections/_product/index.md
> +MapsPeople do not sell Indoor Positioning Systems, but MapsIndoors integrate with them. If your organisation wants to have precise positioning there is a range of different technologies to consider s
```suggestion

MapsPeople do not sell Indoor Positioning Systems, but MapsIndoors integrate with them. If your organisation wants to have precise positioning there are a range of different technologies to consider such as Beacons, WiFi, ultra-sound etc. You can [read more here](https://blog.mapspeople.com/mapsindoors/indoor-positioning-101).
```

2020-10-13 11:58 UTC, marksdk commented on collections/_product/index.md
> +![MapsIndoors CMS](/assets/product/CMS.png "MapsIndoors CMS")
```suggestion
![MapsIndoors CMS](/assets/product/CMS.png)
```

2020-10-13 11:58 UTC, marksdk commented on collections/_product/index.md
> +![Platforms](/assets/product/Platforms.png "Platforms")
```suggestion
![Platforms](/assets/product/Platforms.png)
```

2020-10-13 11:58 UTC, marksdk commented on collections/_product/index.md
> +![WebApp](/assets/product/webApp.png "WebApp")
```suggestion
![WebApp](/assets/product/webApp.png)
```

2020-10-13 11:59 UTC, marksdk commented on collections/_product/index.md
> +![Kiosk](/assets/product/Kiosk1.png "Kiosk")
```suggestion
![Kiosk](/assets/product/Kiosk1.png)
```

2020-10-13 12:26 UTC, sibo86 commented on collections/_product/index.md
> +When you have a custom MapsIndoors Solution you also get access to the MapsIndoors CMS. Within the CMS you can manage locations within your solution; create, remove, update locations such as rooms, c
What are your thoguhts?

2020-10-13 12:31 UTC, sibo86 commented on collections/_product/index.md
> +Booking integrations are characterised by data flowing in and out of MapsIndoors (read/write). Room bookings can happen directly from MapsIndoors and/or be displayed on the MapsIndoors map. For examp
I more or less took this from the presentation JW held some weeks ago.
What is it that can be misunderstood?

2020-10-13 20:09 UTC, marksdk commented on _layouts/front.html
> +                    <path d="M38 16C38 23.4512 32.9066 29.7127 26.0116 31.4929L22 44L17.9884 31.4929C11.0934 29.7127 6 23.4512 6 16C6 7.16344 13.1634 0 22 0C30.8366 0 38 7.16344 38 16ZM22 21C24.7614
@sibo86 I changed the SVG to another one from Figma and now it works ¯\_(ツ)_/¯

2020-10-14 19:35 UTC, marksdk requested changes
Nice work here—I think it's going to be valuable to have this page to link to going forward 👍

2020-10-14 19:35 UTC, marksdk commented on collections/_product/index.md
> +When you have a custom MapsIndoors Solution you also get access to the MapsIndoors CMS. Within the CMS you can manage locations within your solution; create, remove, update locations such as rooms, c
You can't remove Rooms in the CMS—only POIs. This is to prevent that there's a discrepancy between the geodata created by the digitization team and what's in the CMS.

2020-10-14 19:35 UTC, marksdk commented on collections/_product/index.md
> +### Integration Modules
```suggestion
## Integration Modules
```

2020-10-14 19:35 UTC, marksdk commented on collections/_product/index.md
> +The MapsIndoors Integration API is used to connect 3rd party systems with MapsIndoors in order to feed data into the MapsIndoors solution. The API provides an interface to update data in MapsIndoors
```suggestion
The MapsIndoors Integration API is used to connect 3rd party systems with MapsIndoors in order to feed data into your MapsIndoors Solution. The API provides an interface to update data in MapsIndoors from an external source. An external source could be a Facility Management System that already contains relevant data for your MapsIndoors Solution.
```

2020-10-14 19:35 UTC, marksdk commented on collections/_product/index.md
> +It is possible to update Locations, Rooms, Venues, Buildings, Floors, Areas etc. automatically instead of having to do it manually via the MapsIndoors CMS
```suggestion
It is possible to update Locations, Rooms, Venues, Buildings, Floors, Areas etc. automatically instead of having to do it manually via the MapsIndoors CMS.
```

2020-10-14 19:35 UTC, marksdk commented on collections/_product/index.md
> +Real-time integrations are characterised by displaying data “live” on the map (< 1 min delay). The data is read-only and gathered and distributed on the specific solution, but is never saved/cached f
```suggestion
Real-time integrations are characterised by displaying data “live” on the map (< 1 min delay), for example a live-updating position from a shuttle bus service in an airport. The data is not saved for long-term storage, only briefly cached to ensure delivery to the apps.
```

2020-10-14 19:35 UTC, marksdk commented on collections/_product/index.md
> +Booking integrations are characterised by data flowing in and out of MapsIndoors (read/write). Room bookings can happen directly from MapsIndoors and/or be displayed on the MapsIndoors map. For examp
```suggestion
Booking integrations are characterised by data flowing in and out of MapsIndoors (read/write). Room bookings can happen directly through your app built with MapsIndoors, and you can display the booking status of a meeting room directly on the map, i.e. whether it is vacant or not.
```

2020-10-20 07:56 UTC, simonlaustsen approved these changes
Did review all changes since Marks review.
Approved 👍

2020-10-20 14:04 UTC, marksdk approved these changes

2020-10-26 11:17 UTC, merged