Feature/en/java script sdk v4
MapsIndoors/mapsindoors.github.io pull request #155
Opened 2020-10-14 13:10 UTC by eNepper

2020-10-27 07:04 UTC, eNepper commented on collections/_web/v4/index.md
> +---
@marksdk This page is not accurate for SDK v4 but the only "application" we have right now using v4 is the kiosk, and that one is built with components.

2020-10-29 16:56 UTC, marksdk requested changes

2020-10-29 16:56 UTC, marksdk commented on collections/_web/v4/guides/display_rules_intro.md
> +A DisplayRule defined for a **POI** at runtime.
@eNepper I'm not sure if something's missing here.

2020-10-29 16:56 UTC, marksdk commented on collections/_web/v4/guides/display_rules_intro.md
> +To remove a value from the DisplayRule set the proptery to `null`.
```suggestion

To remove a value from the DisplayRule set the proptery to `null`.
```

2020-10-29 16:56 UTC, marksdk commented on collections/_web/v4/guides/display_rules_intro.md
> +```javascript
```suggestion

```javascript
```

2020-10-29 16:56 UTC, marksdk commented on collections/_web/v4/guides/display_rules_intro.md
> +```javascript
```suggestion

```javascript
```

2020-10-29 16:56 UTC, marksdk commented on collections/_web/v4/guides/display_rules_intro.md
> +-   [Show user location on the map (Blue dot)](/guides/show_users_position/)
```suggestion
- [Create a simple map with MapsIndoors](/guides/simple_map/)
- [Introduction to DispayRules](guides/display_rules_intro/)
- [Search and filtering](/guides/search_and_filtering/)
- [Show user location on the map (Blue dot)](/guides/show_users_position/)
```

Are you sure these links point to the right places?

2020-10-29 16:56 UTC, marksdk commented on collections/_web/v4/guides/search_and_filtering.md
> +It will return a Promise that gets resolved when the query has executed.
```suggestion

It will return a Promise that gets resolved when the query has executed.
```

2020-10-29 16:56 UTC, marksdk commented on collections/_web/v4/guides/search_and_filtering.md
> +
```suggestion
When the function executes, we check to see if the input is empty or not. If the input is not empty, we proceed to construct the request object.

```

2020-10-29 16:56 UTC, marksdk commented on collections/_web/v4/guides/search_and_filtering.md
> +If there are no locations returned, we show a message to the user stating "No results matched the query.". Otherwise, we pass the locations on to the next handler called `filterMap`
```suggestion
If there are no Locations returned, we show a message to the user stating "No results matched the query.". Otherwise, we pass the Locations on to the next handler called `filterMap`
```

2020-10-29 16:56 UTC, marksdk commented on collections/_web/v4/guides/search_and_filtering.md
> +In the `filterMap` helper function, we create a list of `location id`s we can use to filter the POIs on the map by.
```suggestion
In the `filterMap` helper function, we create a list of `location id`s we can use to filter the Locations on the map by.
```

2020-10-29 16:56 UTC, marksdk commented on collections/_web/v4/guides/search_and_filtering.md
> +* [Show user location on the map (Blue dot)](/guides/show_users_position/)
Same as above - are we sure the links are pointing in the right direction?

2020-10-29 16:56 UTC, marksdk commented on collections/_web/v4/guides/using_events.md
> +The event handler is called with a [location](https://app.mapsindoors.com/mapsindoors/js/sdk/latest/docs/global.html#Location) object representing the POI or area clicked.
```suggestion
The event handler is called with a [location](https://app.mapsindoors.com/mapsindoors/js/sdk/latest/docs/global.html#Location) object representing the Location clicked.
```

2020-10-30 11:15 UTC, eNepper commented on collections/_web/v4/guides/using_events.md
> +The event handler is called with a [location](https://app.mapsindoors.com/mapsindoors/js/sdk/latest/docs/global.html#Location) object representing the POI or area clicked.
Are we using the term location or POI?

2020-10-30 11:17 UTC, eNepper commented on collections/_web/v4/guides/display_rules_intro.md
> +A DisplayRule defined for a **POI** at runtime.
Do you feel like something is missing?

2020-10-30 11:46 UTC, eNepper commented on collections/_web/v4/guides/search_and_filtering.md
> +* [Show user location on the map (Blue dot)](/guides/show_users_position/)
Show user location on the map (Blue dot) is not rewritten yet

2020-10-30 11:47 UTC, eNepper commented on collections/_web/v4/guides/search_and_filtering.md
> +* [Show user location on the map (Blue dot)](/guides/show_users_position/)
I think the other links are correct

2020-11-02 11:15 UTC, ammapspeople requested changes

2020-11-02 11:15 UTC, ammapspeople commented on collections/_web/v4/upgrade_guide.md
> +The Directions service now takes a reference to an external Directions provider when initialized. The external provider can either be a Google Maps or a Mapbox provider.
I think we need code examples (v3 vs v4) for this.

2020-11-03 12:57 UTC, eNepper commented on collections/_web/v4/upgrade_guide.md
> +With the introduction of MapsIndoors JavaScript SDK v4, there are some changes to the structure of the APIs. With the added support for Mapbox, we have introduced a new concept called a Map View. A M
Yes

2020-11-05 12:45 UTC, marksdk submitted a review, later dismissed

2020-11-05 12:46 UTC, marksdk approved these changes

2020-11-05 12:56 UTC, marksdk approved these changes

2020-11-05 13:08 UTC, ammapspeople commented on _layouts/front.html
> +                </a>
```suggestion
            </a>
```

2020-11-05 13:12 UTC, ammapspeople commented on collections/_web/v4/guides/search_and_filtering.md
> +date: 2019-11-25
This seems like the wrong date.

2020-11-05 13:16 UTC, ammapspeople commented on collections/_web/v4/index.md
> +The MapsIndoors web application is build on top of Google Maps. You therefore need to get a Google Maps API key.
```suggestion
The MapsIndoors web application is built on top of Google Maps. You therefore need to get a Google Maps API key.
```

2020-11-05 13:23 UTC, ammapspeople commented on collections/_web/v4/upgrade_guide.md
> +How to initiale the SDK has changed. In version 3 of the SDK, MapsIndoors could be initialized directly with the Google Maps map object. In version 4 the map object is created for you by the `mapView
```suggestion
How to initialize the SDK has changed. In version 3 of the SDK, MapsIndoors could be initialized directly with the Google Maps map object. In version 4 the map object is created for you by the `mapView`. You must create a `mapView` either as `GoogleMap` or `MapBox` and hand this `mapView` to MapsIndoors. You can retrieve the created instance of the map using `mapsIndoors.getMap();`.
```

2020-11-05 13:25 UTC, ammapspeople commented on collections/_web/v4/upgrade_guide.md
> +For MapBox the specification of controllers is a bit different than for Google. For Google, the controller setup takes a `div` where MapBox takes an object containing functions returning the `div`.
```suggestion
For MapBox the specification of controls is a bit different than for Google. For Google, the controller setup takes a `div` where MapBox takes an object containing functions returning the `div`.
```

2020-11-05 13:28 UTC, ammapspeople commented on collections/_web/v4/upgrade_guide.md
> +- A "Renderer" to display a given Route on the map and generate the textual description for Directions
The renderer does not generate a textual description. It is part of the response by the provider.

2020-11-05 13:29 UTC, ammapspeople commented on collections/_web/v4/upgrade_guide.md
> +Calculating and displaying a route is still done using the `getRoute()` call, however, the response of this call has been changed for convenience. In version 4 the actual route is returned. In versio
```suggestion
Calculating and displaying a route is still done using the `getRoute()` call, however, the response of this call has been changed for convenience. In version 4 the actual route is returned. In version 3 an array of the route (which always only contained 1 element) was returned, hense the "`response.routes[0]`" can be omitted and the returned route can be sent directly to the renderer for displaying.
```

2020-11-05 13:32 UTC, marksdk commented on collections/_web/v4/upgrade_guide.md
> +- A "Renderer" to display a given Route on the map and generate the textual description for Directions
@ammapspeople How would you suggest we rephrase this line then?

2020-11-05 13:47 UTC, ammapspeople commented on collections/_web/v4/upgrade_guide.md
> +- A "Renderer" to display a given Route on the map and generate the textual description for Directions
@marksdk Something like: A "Renderer" to display a part of a route on the map.

2020-11-05 14:05 UTC, marksdk commented on collections/_web/v4/upgrade_guide.md
> +- A "Renderer" to display a given Route on the map and generate the textual description for Directions
```suggestion
- A "Renderer" to display a given route on the map
```

2020-11-05 14:10 UTC, ammapspeople approved these changes

2020-11-06 08:35 UTC, merged