Feature/en/ jssdk4] introduction to display rules
MapsIndoors/mapsindoors.github.io pull request #159
Opened 2020-10-20 09:30 UTC by eNepper

2020-10-20 10:35 UTC, sibo86 commented on collections/_web/v4/guides/display_rules_intro.md
> +In this, you will be introduced to the concept of Display Rules and learn how you can use Display Rules to change how POIs look on the map.
```suggestion
In this, you will be introduced to the concept of Display Rules and learn how you can use Display Rules to change how POIs are displayed on the map.
```

2020-10-20 10:36 UTC, sibo86 commented on collections/_web/v4/guides/display_rules_intro.md
> +It's possible to apply Display Rules to all POIs of a specific type like `Meeting Rooms` or a single POI using its id.
```suggestion
It is possible to apply Display Rules to a single POI using its ID, or to all POIs of a specific type such as 'Meeting Rooms'.
```

2020-10-20 10:36 UTC, sibo86 commented on collections/_web/v4/guides/display_rules_intro.md
> +You control the default appearance of types and POIs through the MapsIndoors CMS. The Display Rules enable you to change the default appearance dynamically at runtime.
```suggestion
The MapsIndoors CMS is used to control the default appearance of types and POIs. To change the default appearance dynamically at runtime you can use Display Rules.
```

2020-10-20 10:36 UTC, sibo86 commented on collections/_web/v4/guides/display_rules_intro.md
> +It's possible to control different aspects of the appearances like at what zoom levels labels and icons should be visible.
```suggestion
It's possible to control different aspects of the appearance. For example at what zoom levels labels and icons should be visible.
```

2020-10-20 10:37 UTC, sibo86 commented on collections/_web/v4/guides/display_rules_intro.md
> +-   `imageScale` - ????
```suggestion
-   `imageScale` - Defines the size of the image/icon. 1 equals a scale of 1:1, 2 equals a doubling, 3..???
```

2020-10-20 10:40 UTC, sibo86 commented on collections/_web/v4/guides/display_rules_intro.md
> +This enables you to do things like change an icon at a specific zoom level.
```suggestion
This enables you to do things like changing an icon at a specific zoom level.
```

2020-10-20 10:40 UTC, sibo86 commented on collections/_web/v4/guides/display_rules_intro.md
> +It's also possible to highlight POIs when a user clicks on it.
```suggestion
It is also possible to highlight POIs when a user clicks on it.
```

2020-10-20 11:04 UTC, sibo86 commented on collections/_web/v4/guides/simple_map.md
> +For IE11 it's critical to load the MapsIndoors SDK before the Google Maps API due to some conflicting polyfills.
```suggestion
For IE11 it's critical to load the MapsIndoors SDK before the Google Maps API due to conflicting polyfills.
```

2020-10-20 11:05 UTC, sibo86 commented on collections/_web/v4/guides/simple_map.md
> +The MapsIndoors SDK is loaded by using a script tag like so:
```suggestion
The MapsIndoors SDK is loaded by using a script tag like the one below:
```

2020-10-20 11:05 UTC, sibo86 commented on collections/_web/v4/guides/simple_map.md
> +The Google Maps API is loaded by using a script tag like so:
```suggestion
The Google Maps API is loaded by using a script tag like the one below:
```

2020-10-20 11:07 UTC, sibo86 commented on collections/_web/v4/guides/simple_map.md
> +The `libraries` parameter is for loading additional libraries for Google Maps. The MapsIndoors SDK has a dependency on the geometry library.
```suggestion
The `libraries` parameter is for loading additional libraries Google Maps libraries such as XXX. The MapsIndoors SDK has a dependency on the geometry library.
```

2020-10-20 11:08 UTC, sibo86 commented on collections/_web/v4/guides/simple_map.md
> +The `libraries` parameter is for loading additional libraries for Google Maps. The MapsIndoors SDK has a dependency on the geometry library.
XXX skal selvfølgelig erstattes af nogle eksempler på libraries 2-3 stk, hvis det giver mening:) Ellers slet "such as"

2020-10-20 11:10 UTC, sibo86 commented on collections/_web/v4/guides/simple_map.md
> +The `key` parameter contains your application's Google Maps API key. Look [here](https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/get-api-key) For more information abo
```suggestion
The `key` parameter contains your Google Maps API key. Look [here](https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/get-api-key) For more information about how to obtain a key.
```

2020-10-20 11:12 UTC, sibo86 commented on collections/_web/v4/guides/simple_map.md
> +- The `maxZoom` parameter is set to disable the map from zooming further in that level 21.
```suggestion
- The `maxZoom` parameter is set to disable the map from zooming further in that level 21, which is the current maximum.
```

2020-10-20 11:13 UTC, sibo86 commented on collections/_web/v4/guides/simple_map.md
> +Now we create a new instance of the MapsIndoors class and assign the GoogleMapsView to the `mapView` parameter.
```suggestion
A new instance of the MapsIndoors class is created and assigns the GoogleMapsView to the `mapView` parameter.
```

2020-10-20 11:14 UTC, sibo86 commented on collections/_web/v4/guides/simple_map.md
> +This `googleMap.controls[google.maps.ControlPosition.RIGHT_TOP].push(floorSelector);` adds the floor selector to the maps upper right corner as a map control.
```suggestion
`googleMap.controls[google.maps.ControlPosition.RIGHT_TOP].push(floorSelector);` adds the floor selector to upper right corner of the map as a map control.
```

2020-10-20 11:15 UTC, sibo86 commented on collections/_web/v4/guides/using_events.md
> + <script async src="//jsfiddle.net/mapspeople/gex62wzn/embed/html,result/"></script>
```suggestion
```html
 <script async src="//jsfiddle.net/mapspeople/gex62wzn/embed/html,result/"></script>
 ```
```

2020-10-20 11:17 UTC, sibo86 commented on collections/_web/v4/guides/using_events.md
> +This is also related to the floor selector, which will update its view to show the current building floors.
```suggestion
This is also related to the floor selector, which will update its view to show the floors of the current building.
```

2020-10-20 11:19 UTC, sibo86 commented on collections/_web/v4/guides/using_events.md
> +The floor changed will be fired when the floor is changed either by clicking the floor selector or by calling setFloor() on the MapsIndoors instance.
```suggestion
The floor changed event will be fired when the floor is changed; either by clicking the floor selector or by calling `setFloor()` on the MapsIndoors instance.
```

2020-10-20 11:19 UTC, sibo86 commented on collections/_web/v4/guides/using_events.md
> +The click event will fire when the user clicks on a POI or area on the map.
```suggestion
The click event will fire when the user clicks on a POI or an area on the map.
```

2020-10-20 11:56 UTC, eNepper commented on collections/_web/v4/guides/using_events.md
> + <script async src="//jsfiddle.net/mapspeople/gex62wzn/embed/html,result/"></script>
The ```html is not needed here.
This script tag will be rendered as the jsfiddle example.

2020-10-20 12:01 UTC, eNepper commented on collections/_web/v4/guides/simple_map.md
> +The `libraries` parameter is for loading additional libraries for Google Maps. The MapsIndoors SDK has a dependency on the geometry library.
Jeg mener ikke vi skal give eksempler på andet en det som MapsIndoors SDK'et er afhængig af.
```suggestion
The `libraries` parameter is for loading additional libraries for the Google Maps API. The MapsIndoors SDK is dependent on the geometry library from Google.
```

2020-10-20 13:21 UTC, eNepper commented on collections/_web/v4/guides/display_rules_intro.md
> +You control the default appearance of types and POIs through the MapsIndoors CMS. The Display Rules enable you to change the default appearance dynamically at runtime.
```suggestion
The MapsIndoors CMS is used to control the default appearance of types and POIs. To change the default appearance at runtime you can use Display Rules.
```

2020-10-20 14:20 UTC, marksdk requested changes
Very nice job @eNepper 👍

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/display_rules_intro.md
> +In this, you will be introduced to the concept of Display Rules and learn how you can use Display Rules to change how POIs are displayed on the map.
```suggestion
In this guide you will be introduced to the concept of Display Rules and learn how you can use Display Rules to change how POIs are displayed on the map.
```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/display_rules_intro.md
> +It is possible to apply Display Rules to a single POI using its ID, or to all POIs of a specific type such as 'Meeting Rooms'.
```suggestion

It is possible to apply Display Rules to a single POI using its ID, or to all POIs of a specific Location Type such as 'Meeting Rooms'.
```

The linter is unhappy when two paragraphs don't have an empty line between them 🙂

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/display_rules_intro.md
> +The MapsIndoors CMS is used to control the default appearance of types and POIs. To change the default appearance at runtime you can use Display Rules.
```suggestion
The MapsIndoors CMS is used to control the default appearance of Rooms and POIs. To change the default appearance at runtime you can use Display Rules.
```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/display_rules_intro.md
> +It's possible to control different aspects of the appearance. For example at what zoom levels labels and icons should be visible.
```suggestion
It's possible to control different aspects of the appearance. For example at what zoom levels Labels and Icons should be visible.
```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/display_rules_intro.md
> +A Display Rule could looks like this:
```suggestion
A Display Rule could look like this:
```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/display_rules_intro.md
> +It is also possible to highlight POIs when a user clicks on it.
```suggestion

It is also possible to highlight POIs when a user clicks on it.
```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/simple_map.md
> +The `libraries` parameter is for loading additional libraries for the Google Maps API. The MapsIndoors SDK is dependent on the geometry library from Google.
```suggestion
The `libraries` parameter is for loading additional libraries for the Google Maps API. The MapsIndoors SDK is dependent on the Geometry Library from Google.

```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/simple_map.md
> +- The `maxZoom` parameter is set to disable the map from zooming further in that level 21, which is the current maximum.
```suggestion

- `element` is the DOM element on the page that will contain the map. `document.getElementById('map')`
- `center` is the geographical point on which the map is centered.
- `zoom` is the initial zoom level the map will be displayed at.
- The `maxZoom` parameter is set to disable the map from zooming further in that level 21, which is the current maximum.
```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/simple_map.md
> +A reference to the Google Map is obtained by calling getMap on the MapView.
```suggestion

A reference to the Google Map is obtained by calling `getMap` on the `mapView`.

```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/simple_map.md
> +The FloorSelector is created by calling the `new mapsindoors.FloorSelector(floor selector, mapsIndoors);` passing in a DOM element and an instance of MapsIndoors.
```suggestion
The `floorSelector` is created by calling the `new mapsindoors.FloorSelector(floor selector, mapsIndoors);` passing in a DOM element and an instance of MapsIndoors.

```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/simple_map.md
> +---
```suggestion
`googleMap.controls[google.maps.ControlPosition.RIGHT_TOP].push(floorSelector);` adds the Floor Selector to upper right corner of the map as a map control.
```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/using_events.md
> +>-- <cite>[MDN web docs](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events)</cite>
```suggestion
> Events are actions or occurrences that happen in the system you are programming, which the system tells you about so you can respond to them in some way if desired.
>-- <cite>[MDN web docs](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events)</cite>
```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/using_events.md
> +The ready event will be fired when MapsIndoors is done initializing and is ready to interact.
```suggestion
The `ready` event will be fired when MapsIndoors is done initializing and is ready to interact.
```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/using_events.md
> +The building changed event will be fired when the map is moved around and a new building comes in focus.
```suggestion
The `building_changed` event will be fired when the map is moved around and a new Building comes in focus.

```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/using_events.md
> +This is also related to the floor selector, which will update its view to show the floors of the current building.
```suggestion
This is also related to the Floor Selector, which will update its view to show the Floors of the current Building.
```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/using_events.md
> +The floor changed event will be fired when the floor is changed; either by clicking the floor selector or by calling `setFloor()` on the MapsIndoors instance.
```suggestion
The `floor_changed` event will be fired when the Floor is changed; either by clicking the Floor Selector or by calling `setFloor()` on the MapsIndoors instance.
```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/using_events.md
> +The event handler is called with the floor index of the current floor.
```suggestion
The event handler is called with the Floor Index of the current Floor.
```

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/guides/using_events.md
> +The click event will fire when the user clicks on a POI or an area on the map.
```suggestion
The `click` event will fire when the user clicks on a POI or an Area on the map.
```

What about Rooms?

2020-10-20 14:20 UTC, marksdk commented on collections/_web/v4/index.md
> +title: MapsIndoors Web SDK v3
```suggestion
title: MapsIndoors Web SDK v4
```

2020-10-21 06:23 UTC, eNepper commented on collections/_web/v4/guides/display_rules_intro.md
> +The MapsIndoors CMS is used to control the default appearance of types and POIs. To change the default appearance at runtime you can use Display Rules.
Until we implement areas in the SDK I would like to keep rooms out of this. Anders and I will talk about how the interface for styling polygons on the map with display rules should be. If we add rooms now we can't change the interface afterward.

2020-10-21 06:44 UTC, eNepper commented on collections/_web/v4/guides/display_rules_intro.md
> +It is possible to control different aspects of the appearance. For example at what zoom levels labels and icons should be visible.
```suggestion
It is possible to control different aspects of the appearance. For example at what zoom levels Labels and Icons should be visible.
```

2020-10-21 06:59 UTC, eNepper commented on collections/_web/v4/index.md
> +---
@marksdk This page is not accurate for SDK v4 but the only "application" we have right now using v4 is the kiosk, and that one is built with components.

2020-10-21 08:04 UTC, ammapspeople commented on collections/_web/v4/guides/display_rules_intro.md
> +It is only properties with a value that will override the prevoius value. If the value is undefined the prevoius value will be used.
```suggestion
It is only properties with a value that will override the previous value. If the value is undefined the previous value will be used.  
```

2020-10-21 08:08 UTC, ammapspeople commented on collections/_web/v4/guides/display_rules_intro.md
> +
I suggest a heading here, something like "How to set Display Rules using the JavaScript SDK"

2020-10-21 08:09 UTC, ammapspeople commented on collections/_web/v4/guides/display_rules_intro.md
> +
And an explanation of what `mi` refers to.

2020-10-21 08:12 UTC, ammapspeople commented on collections/_web/v4/guides/display_rules_intro.md
> +
I like the wording from the iOS section that tries to describe what a display rule is: "A Display Rule encapsulates both what, how and when a Location should be displayed on the map." (except we use POI instead of Location).

2020-10-21 08:14 UTC, ammapspeople commented on collections/_web/v4/guides/display_rules_intro.md
> +All properties are optional and will only be applied if a value.
```suggestion
All properties are optional.
```

2020-10-21 08:17 UTC, ammapspeople commented on collections/_web/v4/guides/display_rules_intro.md
> +| label         | string  | Descriptive text for the POI. This can either be a static text or a dynamic text, retrieved from a property on the POI. E.g. `"{{ "{{ name " }}}}"` or a combination `"Room
```suggestion
| label         | string  | Descriptive text for the POI. This can either be a static text or a dynamic text, retrieved from a property on the POI, using double curly braces as delimiters. E.g. `"{{ "{{ name " }}}}"` or a combination `"Room: {{ "{{ name " }}}}"`.  |
```

2020-10-21 08:32 UTC, ammapspeople commented on collections/_web/v4/guides/display_rules_intro.md
> +It is possible to control different aspects of the appearance. For example at what zoom levels Labels and Icons should be visible.
Here we could add more use case examples. Do we know of common display rule usages from some of our customers?

2020-10-21 08:34 UTC, ammapspeople commented on collections/_web/v4/guides/display_rules_intro.md
> +
```suggestion
## Display Rule hierarchy
```

2020-10-21 08:34 UTC, ammapspeople commented on collections/_web/v4/guides/display_rules_intro.md
> +
```suggestion
## Display Rule properties
```

2020-10-21 08:37 UTC, ammapspeople commented on collections/_web/v4/guides/display_rules_intro.md
> +It is also possible to highlight POIs when a user clicks on it.
A full example of that would be nice.

2020-10-21 08:39 UTC, marksdk commented on collections/_web/v4/guides/display_rules_intro.md
> +The MapsIndoors CMS is used to control the default appearance of types and POIs. To change the default appearance at runtime you can use Display Rules.
Got it 🤝

2020-10-27 07:05 UTC, eNepper commented on collections/_web/v4/guides/display_rules_intro.md
> +It is possible to control different aspects of the appearance. For example at what zoom levels Labels and Icons should be visible.
Has been merged with https://github.com/MapsIndoors/mapsindoors.github.io/pull/155/

2020-10-27 07:05 UTC, eNepper commented on collections/_web/v4/guides/display_rules_intro.md
> +
Has been merged with https://github.com/MapsIndoors/mapsindoors.github.io/pull/155/files

2020-10-27 07:07 UTC, eNepper commented on collections/_web/v4/guides/display_rules_intro.md
> +-   `imageScale` - ????
Has been merged with https://github.com/MapsIndoors/mapsindoors.github.io/pull/155/files

2020-10-27 07:07 UTC, closed without merging

2020-10-27 07:07 UTC, eNepper commented
Has been merged into https://github.com/MapsIndoors/mapsindoors.github.io/pull/155/files