MIAJS-1306 - Print map doc
MapsIndoors/mapsindoors.github.io pull request #165
Opened 2020-11-04 12:19 UTC by simonlaustsen

I've added a few lines about this silly feature and attached some screenshots.
You are welcome to add more if you like :)

2020-11-05 13:50 UTC, marksdk requested changes

2020-11-05 13:50 UTC, marksdk commented on collections/_various/map_print.md
> +The print map tool can be used for different purposes fx. to print evacuation routes for each floor at your venue.
```suggestion
The print map tool is found in the Standard Web App and can be used for different purposes, e.g. to print evacuation routes for each Floor at your Venue.
```

2020-11-05 13:50 UTC, marksdk commented on collections/_various/map_print.md
> +The print preview can be triggered by the print button at top right or by one of the following shortcuts:
```suggestion
The print preview can be triggered by the print button in the top right corner of the map view in the Standard Web App, or by one of the following shortcuts:
```

2020-11-05 13:50 UTC, marksdk commented on collections/_various/map_print.md
> +which triggers a full screen map print preview as seen below
```suggestion
Clicking the button, or hitting the keyboard combination, triggers a full screen map print preview as seen here:
```

2020-11-05 13:50 UTC, marksdk commented on collections/_various/map_print.md
> +date: 2020-01-31
```suggestion
date: 2020-11-06
```

2020-11-05 13:50 UTC, marksdk commented on collections/_various/map_print.md
> +title: Web App - Print map
```suggestion
title: Print map
```

2020-11-06 12:47 UTC, simonlaustsen commented
All comments resolved :)

2020-11-06 12:55 UTC, marksdk approved these changes

2020-11-06 12:59 UTC, merged